Manhattan\Bundle\PostsBundle\Entity\Image:
    type:  entity
    table: news_image

    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        mime_type:
            type: string
            length: 255
        filename:
            type: string
            length: 255
        createdAt:
            type: datetime
            column: created_at
        updatedAt:
            type: datetime
            column: updated_at

    lifecycleCallbacks:
        prePersist:
            - preUpload
            - prePersist
        preUpdate:
            - preUpdateAsset
            - preUpdate
        postPersist:
            - upload
        postUpdate:
            - replace
        preRemove:
            - storeFilenameForRemove
        postRemove:
            - removeUpload
