AGBNews:
    resource: "@AGBNewsBundle/Controller/PostController.php"
    type:     annotation

AGBNewsCategory:
    resource: "@AGBNewsBundle/Controller/CategoryController.php"
    type:     annotation
