ManhattanPosts:
    resource: "@ManhattanPostsBundle/Controller/PostController.php"
    type:     annotation

ManhattanPostsCategory:
    resource: "@ManhattanPostsBundle/Controller/CategoryController.php"
    type:     annotation
