<?php

namespace AGB\Bundle\NewsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends EntityRepository
{
    /**
     * Returns Categories with joined Posts
     */
    public function getCategoriesJoinPost()
    {
        $query = $this->getEntityManager()
            ->createQuery('
                SELECT category, post FROM AGBNewsBundle:Category category
                JOIN category.posts post'
            );

        try {
            return $query->getResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }

}
