<?php

namespace AGB\Bundle\NewsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DocumentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DocumentRepository extends EntityRepository
{
    /**
     * Returns Document with joined Post
     * 
     * @param  int      $id
     * @return Document
     */
    public function findOneByIdJoinPost($id)
    {
        $query = $this->getEntityManager()
            ->createQuery('
                SELECT document, post FROM AGBNewsBundle:Document document
                LEFT JOIN document.post post
                WHERE document.id = :id'
            )->setParameters(array(
                'id' => $id
        ));

        try {
            return $query->getSingleResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }

}
