<?php

namespace Manhattan\Bundle\PostsBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * DocumentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AttachmentRepository extends EntityRepository
{
    /**
     * Returns Document with joined Post
     *
     * @param  int      $id
     * @return Document
     */
    public function findOneByIdJoinPost($id)
    {
        $query = $this->getEntityManager()
            ->createQuery('
                SELECT attachment, post FROM ManhattanPostsBundle:Document attachment
                LEFT JOIN attachment.post post
                WHERE attachment.id = :id'
            )->setParameters(array(
                'id' => $id
        ));

        try {
            return $query->getSingleResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }

}
