<?php

namespace Manhattan\Bundle\PostsBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends EntityRepository
{
    /**
     * Returns Categories with joined Posts
     */
    public function getCategoriesJoinPost()
    {
        $qb = $this->_em->createQueryBuilder();

        $qb->select('category, post')
            ->from('Manhattan\Bundle\PostsBundle\Entity\Category', 'category')
            ->leftJoin('category.posts', 'post');

        try {
            return $qb->getQuery()->getResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }

}
